### ISSUE TITLE
error listening on :8080: listen tcp :8080: bind: address already in use

### ISSUE THREAD

**Issue by 13567436138** [solo-io/wasm#157] opened 2020-08-14 07:39 UTC
```
[root@master01 demo2]# wasme deploy istio webassemblyhub.io/hxpmark/hello:v0.0.1 --id=hello --namespace=istio --labels app=productpage -v
INFO[0000] cache namespace already exists                cache=wasme-cache.wasme image="quay.io/solo-io/wasme:dev"
INFO[0000] cache configmap already exists                cache=wasme-cache.wasme image="quay.io/solo-io/wasme:dev"
INFO[0000] cache service account already exists          cache=wasme-cache.wasme image="quay.io/solo-io/wasme:dev"
INFO[0000] cache role updated                            cache=wasme-cache.wasme image="quay.io/solo-io/wasme:dev"
INFO[0000] cache rolebinding updated                     cache=wasme-cache.wasme image="quay.io/solo-io/wasme:dev"
INFO[0000] cache daemonset updated                       cache=wasme-cache.wasme image="quay.io/solo-io/wasme:dev"
Error: error listening on :8080: listen tcp :8080: bind: address already in use
Usage:
  wasme deploy istio <image> --id=<unique name> [--config=<inline string>] [--root-id=<root id>] [--namespaces <comma separated namespaces>] [--name deployment-name] [flags]

how to change 8080 port
```

**Comment by yuval-k** [comment] 2020-08-25 13:14
@ilackarms do you know where 8080 is coming from?

**Comment by 13567436138** [comment] 2020-08-26 03:45
k8s

**Comment by Sodman** [comment] 2020-10-28 20:41
Closing this as a duplicate of https://github.com/solo-io/wasm/issues/128 - we can track the discussion there.

**Closed by Sodman** 2020-10-28 20:41 UTC
Labels: duplicate
