### ISSUE TITLE
wasme deploy fails when configuration contains zipkin config 

### ISSUE THREAD

**Issue by asayah** [solo-io/wasm#261] opened 2021-04-28 23:41 UTC
add: 
```
spec:
  bindAddress: '::'
  bindPort: 8080
  httpGateway:
    options:
      httpConnectionManagerSettings:
        tracing:
          verbose: true
          requestHeadersForTags:
            - path
            - origin
          zipkinConfig:
            collectorEndpoint: /api/v2/spans
            collectorEndpointVersion: HTTP_JSON
            collectorUpstreamRef:
              name: zipkin
              namespace: default
  proxyNames:
  - gateway-proxy
  ssl: false
```
then 
```
--- ~ » wasme deploy gloo webassemblyhub.io/asayah/add-header:v0.2 --id=add-header                                                                                                                                                    130 ↵
Error: All attempts fail:
#1: converting output crd: reading crd spec on resource gateway-proxy in namespace gloo-system into v1Gateway: unknown field "zipkinConfig" in tracing.ListenerTracingSettings
```

**Comment by Sodman** [comment] 2021-05-13 15:59
What versions of Gloo & wasme were you using when you hit this? Looks like we just need to bump the gloo dependency to something newer, as wasme is missing the new fields.

**Comment by Sodman** [comment] 2021-06-07 23:56
Will also be fixed when https://github.com/solo-io/wasm/issues/257 is done, same root cause, closing as duplicate.

**Closed by Sodman** 2021-06-07 23:56 UTC
Labels: bug
