### ISSUE TITLE
No stored credential for webassemblyhub.io

### ISSUE THREAD

**Issue by djannot** [solo-io/wasm#120] opened 2020-05-29 17:18 UTC
I login with `wasme login -u $YOUR_USERNAME -p $YOUR_PASSWORD`

Then, I can push image.

But when I try to deploy it I get the following error:

```
$ wasme deploy gloo webassemblyhub.io/$YOUR_USERNAME/add-header:v0.1 --id=add-header
Error: All attempts fail:
#1: error getting credentials - err: exit status 1, out: `No stored credential for webassemblyhub.io`
Usage:
  wasme deploy gloo <image> --id=<unique name> [--config=<inline string>] [--root-id=<root id>] [--namespaces <comma separated namespaces>] [--labels <key1=val1,key2=val2>] [flags]

Flags:
  -h, --help                    help for gloo
  -l, --labels stringToString   select deploy the filter to selected Gateway resource in the given namespaces. if none provided, Gateways in all namespaces will be selected. (default [])
  -n, --namespaces strings      deploy the filter to selected Gateway resource in the given namespaces. if none provided, Gateways in all namespaces will be selected.

Global Flags:
      --config string    optional config that will be passed to the filter. accepts an inline string.
      --id string        unique id for naming the deployed filter. this is used for logging as well as removing the filter. when running wasme deploy istio, this name must be a valid Kubernetes resource name.
      --root-id string   optional root ID used to bind the filter at the Envoy level. this value is normally read from the filter image directly.
  -v, --verbose          verbose output
```

**Comment by Sodman** [comment] 2020-10-29 18:11
Unable to reproduce in latest version of wasme. Closing for now, if you are still having issues we can re-open!

**Closed by Sodman** 2020-10-29 18:11 UTC
